name: Process and Extract Assets

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Unzip the "zbbig2.zip" file and list files in "assets"
        run: |
          unzip zbbig2.zip -d temp_dir
          find temp_dir/assets/ -type f > all_assets.txt

      - name: Split file list into 5 parts
        run: |
          split -n l/5 all_assets.txt assets_chunk_
          for i in {a..e}; do mv assets_chunk_$i chunk_$((10#$(echo $i | tr 'a-e' '0-4'))).txt; done

      - name: Push chunk files to repo
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add chunk_*.txt
          git commit -m "Added chunk files"
          git push

  process_files:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chunk: [0, 1, 2, 3, 4]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create folder for extraction
        run: mkdir -p "extracted_${{ matrix.chunk }}"

      - name: Extract files from chunk_${{ matrix.chunk }}.txt
        run: |
          while read file; do
            unzip -j zbbig2.zip "$file" -d "extracted_${{ matrix.chunk }}"
          done < chunk_${{ matrix.chunk }}.txt

      - name: Pause after extraction
        run: sleep 10

      - name: Push extracted files to repo
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add extracted_${{ matrix.chunk }}
          git commit -m "Added extracted files from chunk_${{ matrix.chunk }}"
          git push

      - name: Clean up extracted files to save storage
        run: rm -rf "extracted_${{ matrix.chunk }}"

  finalize:
    needs: process_files
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup chunks after processing
        run: rm -f chunk_*.txt
